### ISSUE TITLE
Checkout api implementation

### ISSUE THREAD

**Issue by Sandvoxel** [kcable194/squareup#1]
I'm willing to help out and try to make a pr but I was unsure what the direction of the project was.

**Comment by kcable194** [comment]
PR's are welcome for sure! I'm not sure if this answers your question but my vision for the project would be to provide all of the Square API implementations such that someone can write custom scripts/applications for any given business. This is my current use case. I also envision another Client implementation that would better allow someone to develop a SaaS product that serves multiple businesses.

**Comment by Sandvoxel** [comment]
Cool I'll definitely try to get that cr some time this week.
